"""add access log fields

Revision ID: 19e1c91c1946
Revises: b399f6d685a8
Create Date: 2026-09-09 13:36:35.693633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e1c91c1946'
down_revision: Union[str, Sequence[str], None] = 'b399f6d685a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_events', sa.Column('client_ip', sa.String(length=45), nullable=True))
    op.add_column('log_events', sa.Column('http_version', sa.String(length=20), nullable=True))
    op.add_column('log_events', sa.Column('response_size', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_log_events_client_ip'), 'log_events', ['client_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_events_client_ip'), table_name='log_events')
    op.drop_column('log_events', 'response_size')
    op.drop_column('log_events', 'http_version')
    op.drop_column('log_events', 'client_ip')
    # ### end Alembic commands ###
