"""add normalized evidence

Revision ID: 1ca0a68185bc
Revises: 19e1c91c1946
Create Date: 2026-09-14 13:24:45.779904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca0a68185bc'
down_revision: Union[str, Sequence[str], None] = '19e1c91c1946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normalized_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_event_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('layer', sa.String(length=100), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.Column('build_id', sa.String(length=255), nullable=True),
    sa.Column('deployment_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['log_event_id'], ['log_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_evidence_build_id'), 'normalized_evidence', ['build_id'], unique=False)
    op.create_index(op.f('ix_normalized_evidence_deployment_id'), 'normalized_evidence', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_normalized_evidence_environment'), 'normalized_evidence', ['environment'], unique=False)
    op.create_index(op.f('ix_normalized_evidence_event_type'), 'normalized_evidence', ['event_type'], unique=False)
    op.create_index(op.f('ix_normalized_evidence_host'), 'normalized_evidence', ['host'], unique=False)
    op.create_index(op.f('ix_normalized_evidence_layer'), 'normalized_evidence', ['layer'], unique=False)
    op.create_index(op.f('ix_normalized_evidence_log_event_id'), 'normalized_evidence', ['log_event_id'], unique=False)
    op.create_index(op.f('ix_normalized_evidence_service'), 'normalized_evidence', ['service'], unique=False)
    op.create_index(op.f('ix_normalized_evidence_severity'), 'normalized_evidence', ['severity'], unique=False)
    op.create_index(op.f('ix_normalized_evidence_source'), 'normalized_evidence', ['source'], unique=False)
    op.create_index(op.f('ix_normalized_evidence_status'), 'normalized_evidence', ['status'], unique=False)
    op.create_index(op.f('ix_normalized_evidence_timestamp'), 'normalized_evidence', ['timestamp'], unique=False)
    op.create_index(op.f('ix_normalized_evidence_trace_id'), 'normalized_evidence', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normalized_evidence_trace_id'), table_name='normalized_evidence')
    op.drop_index(op.f('ix_normalized_evidence_timestamp'), table_name='normalized_evidence')
    op.drop_index(op.f('ix_normalized_evidence_status'), table_name='normalized_evidence')
    op.drop_index(op.f('ix_normalized_evidence_source'), table_name='normalized_evidence')
    op.drop_index(op.f('ix_normalized_evidence_severity'), table_name='normalized_evidence')
    op.drop_index(op.f('ix_normalized_evidence_service'), table_name='normalized_evidence')
    op.drop_index(op.f('ix_normalized_evidence_log_event_id'), table_name='normalized_evidence')
    op.drop_index(op.f('ix_normalized_evidence_layer'), table_name='normalized_evidence')
    op.drop_index(op.f('ix_normalized_evidence_host'), table_name='normalized_evidence')
    op.drop_index(op.f('ix_normalized_evidence_event_type'), table_name='normalized_evidence')
    op.drop_index(op.f('ix_normalized_evidence_environment'), table_name='normalized_evidence')
    op.drop_index(op.f('ix_normalized_evidence_deployment_id'), table_name='normalized_evidence')
    op.drop_index(op.f('ix_normalized_evidence_build_id'), table_name='normalized_evidence')
    op.drop_table('normalized_evidence')
    # ### end Alembic commands ###
