"""add incident intelligence models

Revision ID: 48b92c5292a6
Revises: 255b045ebe11
Create Date: 2026-08-31 18:49:38.949871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b92c5292a6'
down_revision: Union[str, Sequence[str], None] = '255b045ebe11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='open', nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_incident_key'), 'incidents', ['incident_key'], unique=True)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_start_time'), 'incidents', ['start_time'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('request_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_rate', sa.Float(), server_default='0', nullable=False),
    sa.Column('average_latency', sa.Float(), server_default='0', nullable=False),
    sa.Column('p95_latency', sa.Float(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service', 'timestamp', name='uq_metrics_service_timestamp')
    )
    op.create_index(op.f('ix_metrics_service'), 'metrics', ['service'], unique=False)
    op.create_index(op.f('ix_metrics_timestamp'), 'metrics', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_created_at'), 'ai_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_analyses_incident_id'), 'ai_analyses', ['incident_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anomaly_type', sa.String(length=100), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_anomaly_type'), 'anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_metric_id'), 'anomalies', ['metric_id'], unique=False)
    op.create_index(op.f('ix_anomalies_service'), 'anomalies', ['service'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.create_index(op.f('ix_anomalies_timestamp'), 'anomalies', ['timestamp'], unique=False)
    op.create_table('copilot_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_messages_created_at'), 'copilot_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_copilot_messages_incident_id'), 'copilot_messages', ['incident_id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_role'), 'copilot_messages', ['role'], unique=False)
    op.create_index(op.f('ix_copilot_messages_user_id'), 'copilot_messages', ['user_id'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_event_type'), 'incident_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_events_source'), 'incident_events', ['source'], unique=False)
    op.create_index(op.f('ix_incident_events_timestamp'), 'incident_events', ['timestamp'], unique=False)
    op.create_table('incident_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('impact_level', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'service', name='uq_incident_services_incident_service')
    )
    op.create_index(op.f('ix_incident_services_impact_level'), 'incident_services', ['impact_level'], unique=False)
    op.create_index(op.f('ix_incident_services_incident_id'), 'incident_services', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_services_service'), 'incident_services', ['service'], unique=False)
    op.create_table('log_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('total_entries', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_files_environment'), 'log_files', ['environment'], unique=False)
    op.create_index(op.f('ix_log_files_service'), 'log_files', ['service'], unique=False)
    op.create_index(op.f('ix_log_files_uploaded_at'), 'log_files', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_log_files_uploaded_by'), 'log_files', ['uploaded_by'], unique=False)
    op.create_table('log_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_file_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['log_file_id'], ['log_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_events_endpoint'), 'log_events', ['endpoint'], unique=False)
    op.create_index(op.f('ix_log_events_environment'), 'log_events', ['environment'], unique=False)
    op.create_index(op.f('ix_log_events_host'), 'log_events', ['host'], unique=False)
    op.create_index(op.f('ix_log_events_level'), 'log_events', ['level'], unique=False)
    op.create_index(op.f('ix_log_events_log_file_id'), 'log_events', ['log_file_id'], unique=False)
    op.create_index(op.f('ix_log_events_method'), 'log_events', ['method'], unique=False)
    op.create_index(op.f('ix_log_events_service'), 'log_events', ['service'], unique=False)
    op.create_index(op.f('ix_log_events_status_code'), 'log_events', ['status_code'], unique=False)
    op.create_index(op.f('ix_log_events_timestamp'), 'log_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_log_events_trace_id'), 'log_events', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_events_trace_id'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_timestamp'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_status_code'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_service'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_method'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_log_file_id'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_level'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_host'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_environment'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_endpoint'), table_name='log_events')
    op.drop_table('log_events')
    op.drop_index(op.f('ix_log_files_uploaded_by'), table_name='log_files')
    op.drop_index(op.f('ix_log_files_uploaded_at'), table_name='log_files')
    op.drop_index(op.f('ix_log_files_service'), table_name='log_files')
    op.drop_index(op.f('ix_log_files_environment'), table_name='log_files')
    op.drop_table('log_files')
    op.drop_index(op.f('ix_incident_services_service'), table_name='incident_services')
    op.drop_index(op.f('ix_incident_services_incident_id'), table_name='incident_services')
    op.drop_index(op.f('ix_incident_services_impact_level'), table_name='incident_services')
    op.drop_table('incident_services')
    op.drop_index(op.f('ix_incident_events_timestamp'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_source'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_event_type'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_copilot_messages_user_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_role'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_incident_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_created_at'), table_name='copilot_messages')
    op.drop_table('copilot_messages')
    op.drop_index(op.f('ix_anomalies_timestamp'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_service'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_metric_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_type'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_ai_analyses_incident_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_created_at'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_metrics_timestamp'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_service'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_start_time'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_key'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
