"""add incident signals

Revision ID: 50ca0aabc9f2
Revises: 6ab76e64040c
Create Date: 2026-09-15 21:00:42.952133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50ca0aabc9f2'
down_revision: Union[str, Sequence[str], None] = '6ab76e64040c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('baseline', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_signals_created_at'), 'incident_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_signals_incident_id'), 'incident_signals', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_signals_signal_time'), 'incident_signals', ['signal_time'], unique=False)
    op.create_index(op.f('ix_incident_signals_signal_type'), 'incident_signals', ['signal_type'], unique=False)
    op.drop_index(op.f('ix_incident_evidence_incident_id'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_linked_at'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_normalized_evidence_id'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_relationship_type'), table_name='incident_evidence')
    op.drop_table('incident_evidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_evidence',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('normalized_evidence_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relationship_type', sa.VARCHAR(length=50), server_default=sa.text("'supporting'::character varying"), autoincrement=False, nullable=False),
    sa.Column('linked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('incident_evidence_incident_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['normalized_evidence_id'], ['normalized_evidence.id'], name=op.f('incident_evidence_normalized_evidence_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_evidence_pkey')),
    sa.UniqueConstraint('incident_id', 'normalized_evidence_id', name=op.f('uq_incident_evidence'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_incident_evidence_relationship_type'), 'incident_evidence', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_incident_evidence_normalized_evidence_id'), 'incident_evidence', ['normalized_evidence_id'], unique=False)
    op.create_index(op.f('ix_incident_evidence_linked_at'), 'incident_evidence', ['linked_at'], unique=False)
    op.create_index(op.f('ix_incident_evidence_incident_id'), 'incident_evidence', ['incident_id'], unique=False)
    op.drop_index(op.f('ix_incident_signals_signal_type'), table_name='incident_signals')
    op.drop_index(op.f('ix_incident_signals_signal_time'), table_name='incident_signals')
    op.drop_index(op.f('ix_incident_signals_incident_id'), table_name='incident_signals')
    op.drop_index(op.f('ix_incident_signals_created_at'), table_name='incident_signals')
    op.drop_table('incident_signals')
    # ### end Alembic commands ###
