"""add incident evidence relationships

Revision ID: 6ab76e64040c
Revises: 1ca0a68185bc
Create Date: 2026-09-15 19:11:48.059537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab76e64040c'
down_revision: Union[str, Sequence[str], None] = '1ca0a68185bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('normalized_evidence_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), server_default='supporting', nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['normalized_evidence_id'], ['normalized_evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'normalized_evidence_id', name='uq_incident_evidence')
    )
    op.create_index(op.f('ix_incident_evidence_incident_id'), 'incident_evidence', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_evidence_linked_at'), 'incident_evidence', ['linked_at'], unique=False)
    op.create_index(op.f('ix_incident_evidence_normalized_evidence_id'), 'incident_evidence', ['normalized_evidence_id'], unique=False)
    op.create_index(op.f('ix_incident_evidence_relationship_type'), 'incident_evidence', ['relationship_type'], unique=False)
    op.add_column('incidents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('service', sa.String(length=100), nullable=False))
    op.add_column('incidents', sa.Column('environment', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_incidents_environment'), 'incidents', ['environment'], unique=False)
    op.create_index(op.f('ix_incidents_service'), 'incidents', ['service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_service'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_environment'), table_name='incidents')
    op.drop_column('incidents', 'environment')
    op.drop_column('incidents', 'service')
    op.drop_column('incidents', 'description')
    op.drop_index(op.f('ix_incident_evidence_relationship_type'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_normalized_evidence_id'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_linked_at'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_incident_id'), table_name='incident_evidence')
    op.drop_table('incident_evidence')
    # ### end Alembic commands ###
