"""add log parsing statistics

Revision ID: b399f6d685a8
Revises: c203e8991ff2
Create Date: 2026-09-09 13:23:21.848983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b399f6d685a8'
down_revision: Union[str, Sequence[str], None] = 'c203e8991ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_files', sa.Column('total_lines', sa.Integer(), server_default='0', nullable=False))
    op.add_column('log_files', sa.Column('parsed_lines', sa.Integer(), server_default='0', nullable=False))
    op.add_column('log_files', sa.Column('skipped_lines', sa.Integer(), server_default='0', nullable=False))
    op.add_column('log_files', sa.Column('malformed_lines', sa.Integer(), server_default='0', nullable=False))
    op.add_column('log_files', sa.Column('unknown_format_lines', sa.Integer(), server_default='0', nullable=False))
    op.add_column('log_files', sa.Column('parser_errors', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_files', 'parser_errors')
    op.drop_column('log_files', 'unknown_format_lines')
    op.drop_column('log_files', 'malformed_lines')
    op.drop_column('log_files', 'skipped_lines')
    op.drop_column('log_files', 'parsed_lines')
    op.drop_column('log_files', 'total_lines')
    # ### end Alembic commands ###
