"""add log ingestion metadata

Revision ID: c203e8991ff2
Revises: db5e2af9a199
Create Date: 2026-09-03 23:40:10.421992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c203e8991ff2'
down_revision: Union[str, Sequence[str], None] = 'db5e2af9a199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_files', sa.Column('file_type', sa.String(length=20), nullable=False))
    op.add_column('log_files', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('log_files', sa.Column('processing_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('log_files', sa.Column('error_message', sa.String(length=1000), nullable=True))
    op.add_column('log_files', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_log_files_processing_status'), 'log_files', ['processing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_files_processing_status'), table_name='log_files')
    op.drop_column('log_files', 'processed_at')
    op.drop_column('log_files', 'error_message')
    op.drop_column('log_files', 'processing_status')
    op.drop_column('log_files', 'file_size')
    op.drop_column('log_files', 'file_type')
    # ### end Alembic commands ###
